version: '3.5'

services:

  yellow-pages-angular:
    container_name: yellow-pages-angular
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '4200:4200'